#!/bin/bash

set -eu -o pipefail # fail on error and report it, debug all lines

sudo -n true
test $? -eq 0 || exit 1 "you should have sudo privilege to run this script"

echo installing the must-have pre-requisites
while read -r p ; do sudo apt-get install --dry-run $p ; done < <(cat << "EOF"
    unity8-fake-env
    git
    unity8-private
    unity8
    unity8-common
    luckybackup
    luckybackup-data
    tasksel
    whohas
    ubuntukylin-desktop
    ubuntukylin-default-settings
    ubuntu-desktop-mir
    curl
    wget
EOF
)

echo "installing the nice-to-have pre-requisites"
echo "you have 5 seconds to proceed ..."
echo "or"
echo "hit Ctrl+C to quit"
echo -e "\n"
sleep 6

sudo apt-get install -y tig

